### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by netlander** [zeroxme/bootstrap-3-arabic#18]
Is this project dead?

**Comment by zeroxme** [comment]
Nope. I'm just a bit busy beside I'm waiting for Bootstrap 4. If you need any help or if you have anu questions feel free to post them

**Comment by netlander** [comment]
The package is way out of date (bootstrap is at 3.3.5) and is also not well put together as the docs folder is broken.
Some example pages would be great to allow new users to get up to speed with your dist.

**Comment by zeroxme** [comment]
Yes I will update. I'll have some time during the upcoming 2 weeks :) ... thanks for kicking my ass to get back on it again :dancers:

**Comment by zeroxme** [comment]
@netlander updated :)
