### ISSUE TITLE
`body{}`

### ISSUE THREAD

**Issue by mahmoudZakaria90** [zeroxme/bootstrap-3-arabic#20]

**Comment by zeroxme** [comment]
Please explain. You opened 2 issues without a discription

**Comment by mahmoudZakaria90** [comment]
i didn't press on comment button ! how 2 issues came to you ?!
by the way sorry for that

**Comment by zeroxme** [comment]
No problem

**Comment by mahmoudZakaria90** [comment]
ok can you re open again as i want to ask about giving the body direction : rtl 
because when i did this before any jquery plugin i embed in my document like : gallery slider or simple bootstrap slider  were destroyed 
how can i fix this ?

i tried before this line i've created :
`*:not(body),*:not(div),*:not(html){
direction: rtl
}`
it works
