### ISSUE TITLE
White screen under Chrome for Mac and android

### ISSUE THREAD

**Issue by ghost** [zeroxme/bootstrap-3-arabic#22]
Under Chrome for android or Mac, the page loads, but the screen is white (blank).
No console errors. No network errors.
The file that causes this bug is bootstrap-arabic.min.cs.
The English version under same circumstances does not have this problem.
Thanks,

**Comment by zeroxme** [comment]
Can you please provide an example via [jsfiddle](https://jsfiddle.net/), so I can understand what you mean exactly

**Comment by ghost** [comment]
It is hard to reproduce the bug in jsfiddle.
What happens is that while navigating the website, the page becomes blank unless you scroll down.
I applied the first workaround to handle it:

The first workaround is to scroll the page automatically using JQuery:
   $(document).ready(function () {
            window.scrollBy(0, 1);
            window.scrollBy(0, -1);
        });

The second workaround is to comment padding in this line:
.container {/\* padding-right:15px; padding-left:15px; */ margin-right:auto; margin-left:auto;}

I don't know what causes the problem exactly, but the auto scrolling fixed it in my case.

You may close this (specific) case, but keep it in mind if it happened with another user.
Thanks.

**Comment by zeroxme** [comment]
Thanks for your explanation but I can't track the problem and I just tried to use the css files to see if that exists. The code in the repo matches the original repo except for directions. Maybe the problem exists in your code or browser. Please double check and let me know
